#!/usr/bin/env bash

if [[ ! -d "certs" ]]; then
    >&2 echo "This script must run in the parent dir of certs/"
    exit 1
fi

if [[ "2" != "$#" ]]; then
    >&2 echo "Usage:"
    >&2 echo "  mkdir <geo> [client|server]"
    exit 1
fi

geo=$1
role=$2

if [[ "server" == "$role" ]]; then
    cert_cn="/CN=${geo}.headspin.io"
fi

name="${geo}_${role}"
openssl genrsa -out certs/$name.key 1024
openssl req -new -key certs/$name.key -x509 -days 3653 -out certs/$name.crt -subj "/C=us/ST=ca/L=Mountain View/O=HeadSpin${cert_cn}"
cat certs/$name.key certs/$name.crt > certs/$name.pem
rm certs/$name.key
